---
title: "G0I Regression: Bias-corrected estimation for the GI0 regression"
output: html_document
date: "2024-10-21"
---

### Packages
```{r setup, include=TRUE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(maxLik)  
library(invgamma)
library(knitr)
```

### Random Number Generation of distribution
```{r pressure, echo=TRUE}
G0I.RNG <- function(n, theta)
  rgamma(n, theta[3], theta[3]) * rinvgamma(n, -theta[1], rate = theta[2])
```

### Random Number Generation of Regression Model
```{r}
G0I.Reg <- function(n, X, Z, theta, L){
  # n, sample size
  # X, independent variables
  # Z, dependent variable
  # L, number of looks

# Auxiliares
p <- dim(X)[2]
r <- length(theta)  

Beta  <- theta[1:p]
Delta <- theta[(p+1):r]

Mu  <- exp(X%*%Beta)
Phi <- exp(Z%*%Delta)
  
 vet <- NULL
 for(i in 1:n)
    vet[i] <- G0I.RNG(1, c(-(Phi[i] + 2), (Phi[i] + 1)*Mu[i], L))
  vet
}
```

### Simulated data
```{r}
DataSim <- function(Size, theta){

  if (theta[5] < 0) stop("L is the number of looks, positive integer")

# Variables
X   <- cbind(rep(1, n=Size), runif(n=Size))
Z   <- cbind(rep(1, n=Size), runif(n=Size))

# Simulated data
Data  <- data.frame(y=G0I.Reg(n = Size, X=X, Z=Z, 
                    theta = theta[1:4], L=theta[5]), X = X, Z = Z)
colnames(Data) <- c("y", "x1", "x2", "z1", "z2")

return(Data)
}
```

### Simulated data
```{r}
set.seed(240701) # specify seeds

theta <- c(Beta0=1.0, Beta1=1.0, Delta0=2.0, Delta1=4.0, L=4)
Data <- DataSim(Size=10, theta=theta)
kable(head(Data), align = "c")
```


